### ISSUE TITLE
No UART Comm. when using Zedboard

### ISSUE THREAD

**Issue by somanshraj** [CactiLab/BYOTee-Build-Your-Own-TEEs#2]
Trying to implement app1 example on Zedboard - 

Scenario 1 : Changed the name as per the new Si family chip xc7z020clg484-1
Observations 1 : Board is booting but on pressing reset button no additional terminal is opened.

Scenario 2 : modified all possible changes as per the new Si family chip xc7z020clg484-1
This time created new BOOT.bin, u-boot.elf and replaced in the respective folder

Observation 2 : Board is booting but on pressing reset button has no effect.

Any possible solution will be appreciated.

**Comment by Tomal-kuet** [comment]
Please use the Cora Z7-07S board. All the applications were developed and tested on this board.

If you really need to use Zedboard, we need to change the hardware design. As the hardware projects are developed for Cora Z7-07S, thus the generated bitstream is loadable for this board. After running the build scripts if you open the hardware project with vivado in `pl` folder, it will show Cora Z7-07S as the selected board. 

Besides this, the files in `boot-image` folder inside the application directory may need to be regenerated for the Zedboard.

**Comment by somanshraj** [comment]
Okay! 
 
The reason to understand for Zedboard is that same can be used to implement on different Silicone chips.
Any exact files which needs to be modified will be of great help .

thanks Tomal anyways !

**Comment by Tomal-kuet** [comment]
Yes, the same can be implemented for different Silicone chips. To change the hardware projects we need to change the `create_bd.tcl` and `create_project.tcl` files inside `app1/pl/proj`. This two tcl scripts are responsible to build the hardware projects. We need change the board specification here so that we get the hardware bitstream for zedboard.

**Comment by somanshraj** [comment]
Got it! 
boot-image folder ( u-boot.elf ) as well as BOOT.bin to be updated as well ? 

thanks!

**Comment by Tomal-kuet** [comment]
Yes
